# Generated by Django 4.2.16 on 2026-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_payment_model_and_trade_paid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
